export const GET_POSTS = 'GET_POSTS';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_POSTS_INFO = 'GET_POSTS_INFO';
export const GET_POSTS_COMMENTS = 'GET_POSTS_COMMENTS';
export const GET_LIMITED_COMMENTS = 'GET_LIMITED_COMMENTS';
export const GET_POSTS_REACTION = 'GET_POSTS_REACTION';
export const GET_POSTS_REACTIONS = 'GET_POSTS_REACTIONS';

export const GET_POSTS_PK = 'GET_POSTS_PK';
