name: Build Android
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]  # Adjust the Node.js version to your project's requirements
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm install

      - name: Build Android Release
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: android/app/build/outputs/apk/debug/app-debug.apk
